#!/usr/bin/env bash
#
# Publishes the Homebrew cask for a release into the personal tap.
#
# Writes exactly one file, Casks/battistics.rb, through the GitHub contents
# API. Nothing else in that tap is read, cloned or rewritten, so nothing that
# happens here can reach dothaven or anything added later.
#
# The hash must be of the DMG as published, not as built: notarytool staples
# the ticket into the image after `make dmg` produces it, which changes the
# bytes. Pass the file that was uploaded, or none at all and it fetches the
# one on the release.
#
#   scripts/update-tap.sh 1.1.0                      # hash the published DMG
#   scripts/update-tap.sh 1.1.0 dist/release/x.dmg   # hash a local file
#   DRY_RUN=1 scripts/update-tap.sh 1.1.0            # print, publish nothing

set -euo pipefail

TAP="${BATTISTICS_TAP:-doguyilmaz/homebrew-tap}"
REPO="${BATTISTICS_REPO:-doguyilmaz/battistics}"
CASK_PATH="Casks/battistics.rb"
VERSION="${1:?usage: update-tap.sh <version> [dmg]}"
DMG="${2:-}"

# The workflow token is scoped to this repository and cannot write to the tap,
# so a release publishes the cask only when a token for it exists. Missing is
# not a failure: the release itself is already out, and a stale cask is a
# smaller problem than a red pipeline that stops future ones.
if [ -n "${HOMEBREW_TAP_GITHUB_TOKEN:-}" ]; then
    export GH_TOKEN="$HOMEBREW_TAP_GITHUB_TOKEN"
elif [ -n "${CI:-}" ]; then
    echo "note: HOMEBREW_TAP_GITHUB_TOKEN unset — skipping the cask update for $VERSION." >&2
    echo "      The release is unaffected. Add the secret to publish to $TAP." >&2
    exit 0
fi

if [ -z "$DMG" ]; then
    WORK=$(mktemp -d)
    trap 'rm -rf "$WORK"' EXIT
    gh release download "v$VERSION" --repo "$REPO" \
        --pattern "Battistics-$VERSION.dmg" --dir "$WORK"
    DMG="$WORK/Battistics-$VERSION.dmg"
fi
[ -f "$DMG" ] || { echo "error: $DMG not found" >&2; exit 1; }

SHA=$(shasum -a 256 "$DMG" | cut -d' ' -f1)

# `auto_updates true` is the stanza that keeps Homebrew and Sparkle out of each
# other's way: the app updates itself, so `brew upgrade` leaves it alone rather
# than reinstalling over a copy that is already newer than the cask says.
CASK=$(
    cat <<RUBY
# Generated by scripts/update-tap.sh in doguyilmaz/battistics. DO NOT EDIT.
cask "battistics" do
  version "$VERSION"
  sha256 "$SHA"

  url "https://github.com/$REPO/releases/download/v#{version}/Battistics-#{version}.dmg"
  name "Battistics"
  desc "Battery statistics for the Mac"
  homepage "https://github.com/$REPO"

  livecheck do
    skip "Auto-generated on release."
  end

  auto_updates true
  depends_on macos: :sonoma

  app "Battistics.app"

  uninstall launchctl: "com.doguyilmaz.Battistics.PowerHelper",
            quit:      "com.doguyilmaz.Battistics"

  zap trash: [
    "~/Library/Application Support/Battistics",
    "~/Library/Caches/com.doguyilmaz.Battistics",
    "~/Library/Caches/com.dogukyilmaz.Battistics",
    "~/Library/HTTPStorages/com.doguyilmaz.Battistics",
    "~/Library/HTTPStorages/com.dogukyilmaz.Battistics",
    "~/Library/Preferences/com.doguyilmaz.Battistics.plist",
    "~/Library/Preferences/com.dogukyilmaz.Battistics.plist",
  ]
end
RUBY
)

if [ -n "${DRY_RUN:-}" ]; then
    printf '%s\n' "$CASK"
    exit 0
fi

# Branch on the exit code, not on whether anything came back: `gh api` prints
# its error body to stdout, so a missing file answers with a JSON 404 that is
# every bit as non-empty as a real cask. Reading that as "the file exists"
# sent the first run down the replace path, where looking up the blob sha of a
# file that is not there failed the whole script.
if current=$(gh api "repos/$TAP/contents/$CASK_PATH" \
    -H "Accept: application/vnd.github.raw" 2>/dev/null); then
    exists=1
else
    exists=0
    current=""
fi

if [ "$current" = "$CASK" ]; then
    echo "cask already at $VERSION, nothing to publish"
    exit 0
fi

# The blob sha is required to replace a file and rejected when creating one,
# so the two cases are separate calls rather than one with a maybe-empty
# argument: `"${arr[@]}"` on an empty array is an error under `set -u` in the
# bash macOS ships, which is the bash this runs under.
CONTENT=$(printf '%s\n' "$CASK" | base64 | tr -d '\n')

if [ "$exists" = 1 ]; then
    gh api "repos/$TAP/contents/$CASK_PATH" -X PUT \
        -f "message=Brew cask update for battistics version v$VERSION" \
        -f "content=$CONTENT" \
        -f "sha=$(gh api "repos/$TAP/contents/$CASK_PATH" --jq .sha)" \
        --jq '.commit.html_url'
else
    gh api "repos/$TAP/contents/$CASK_PATH" -X PUT \
        -f "message=Brew cask update for battistics version v$VERSION" \
        -f "content=$CONTENT" \
        --jq '.commit.html_url'
fi
